DROP DATABASE IF EXISTS CACHE_TEST;
CREATE DATABASE CACHE_TEST;
USE CACHE_TEST;
DROP TABLE IF EXISTS `USER`;
CREATE TABLE `USER` (
	`ID`  int(10) NOT NULL AUTO_INCREMENT ,
	`USERNAME`  varchar(30) NULL ,
	`PASSWORD`  varchar(30) NULL ,
	`REALNAME`  varchar(30) NULL ,
	PRIMARY KEY (`ID`)
);